name: CI

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    if: github.ref != 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 100
          filter: "blob:none"

      - uses: jdx/mise-action@60119f926c4aeea4f9d22e43a9a090b920e2e418
      - run: corepack enable
      - run: yarn install --immutable

      - name: Lint
        run: yarn lint

  typecheck:
    name: Type Check
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 100
          filter: "blob:none"

      - uses: jdx/mise-action@60119f926c4aeea4f9d22e43a9a090b920e2e418
      - run: corepack enable
      - run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Type Check
        run: yarn typecheck

  test:
    name: Test (Node ${{ matrix.node }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20, 22, 24]
    env:
      MISE_NODE_VERSION: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 100
          filter: "blob:none"

      - uses: jdx/mise-action@60119f926c4aeea4f9d22e43a9a090b920e2e418
      - run: corepack enable
      - run: yarn install --immutable

      - name: Test
        run: yarn test
