name: CI

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    if: github.ref != 'refs/heads/main'
    runs-on: [Linux]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          filter: "blob:none"

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

  typecheck:
    name: Type Check
    runs-on: [Linux]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          filter: "blob:none"

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: yarn build

      - name: Type Check
        run: yarn typecheck
